name: Docker



on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: File Changes Action
        id: file_changes
        # You may pin to the exact commit or the version.
        # uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        uses: trilom/file-changes-action@v1.2.4
        with:
          # Choose between json (default), or custom delimiter by passing a string, for example ',' for csv variable output
          output: json
          # Choose between json (default), or custom delimiter by passing a string, for example ',' for csv file output.  If you set as json the file output will be suffixed with .json, if you select ',' then the output will be .csv, else .txt will be the output.
          fileOutput: json

      - name: Run tests
        run: |
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
